[package]
name = "rei-vm"
version = "0.1.0"
edition = "2021"
authors = ["Jason Qin"]
description = "Rei VM"
license-file = "LICENSE"

[dependencies]
phantasm-ir = { git = "https://github.com/hyperswine/phantasm.git" }
